//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPhone
    {
        public int Id { get; set; }
        public int PhoneType { get; set; }
        public short DisplayOrder { get; set; }
        public string CountryCode { get; set; }
        public string AreaCode { get; set; }
        public string Prefix { get; set; }
        public string Number { get; set; }
        public long Extension { get; set; }
        public int LastUpdatedById { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string Notes { get; set; }
        public int PersonsId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
